### ISSUE TITLE
Crash when trying to take a picture of the cover

### ISSUE THREAD

**Issue by h5rcode** [h5rcode/BlackBooks#22]
Android version: 19
Device: samsung GT-I9195
App version: 1
--------- beginning of /dev/log/main
01-22 22:46:11.522 W/dalvikvm( 1748): threadid=1: thread exiting with uncaught exception (group=0x4193cda0)
01-22 22:46:11.552 E/com.blackbooks( 1748): Uncaught exception.
01-22 22:46:11.552 E/com.blackbooks( 1748): java.lang.NullPointerException
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at com.blackbooks.fragments.BookEditGeneralFragment$4.onItemSelected(BookEditGeneralFragment.java:266)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.AdapterView.fireOnSelected(AdapterView.java:964)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.AdapterView.selectionChanged(AdapterView.java:947)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.AdapterView.checkSelectionChanged(AdapterView.java:1114)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.AdapterView.handleDataChanged(AdapterView.java:1094)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:180)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.Spinner.onMeasure(Spinner.java:503)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.View.measure(View.java:17482)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.View.measure(View.java:17482)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1781)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.ScrollView.onMeasure(ScrollView.java:477)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.View.measure(View.java:17482)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.View.measure(View.java:17482)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1456)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.View.measure(View.java:17482)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.View.measure(View.java:17482)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.View.measure(View.java:17482)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:412)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.View.measure(View.java:17482)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.View.measure(View.java:17482)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2287)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2009)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6635)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.Choreographer.doCallbacks(Choreographer.java:613)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.Choreographer.doFrame(Choreographer.java:583)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.os.Handler.handleCallback(Handler.java:733)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.os.Looper.loop(Looper.java:146)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at android.app.ActivityThread.main(ActivityThread.java:5593)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
01-22 22:46:11.552 E/com.blackbooks( 1748): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by h5rcode** [comment]
Refactored the OnItemSelectedListener of mSpinnerLanguage to handle the case of the "view" parameter being null.
