### ISSUE TITLE
Crash when picking an image from the gallery (OutOfMemoryError)

### ISSUE THREAD

**Issue by h5rcode** [h5rcode/BlackBooks#26]
01-31 15:18:03.484 E/com.blackbooks(15623): Uncaught exception.
01-31 15:18:03.484 E/com.blackbooks(15623): java.lang.OutOfMemoryError
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:603)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:626)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at com.blackbooks.utils.BitmapUtils.compress(BitmapUtils.java:43)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at com.blackbooks.fragments.BookEditGeneralFragment.onActivityResult(BookEditGeneralFragment.java:198)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:167)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.app.Activity.dispatchActivityResult(Activity.java:5650)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3676)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3723)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.app.ActivityThread.access$1400(ActivityThread.java:174)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.os.Looper.loop(Looper.java:146)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at android.app.ActivityThread.main(ActivityThread.java:5593)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
01-31 15:18:03.484 E/com.blackbooks(15623): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by h5rcode** [comment]
Changed the implementation of BitmapUtils.compress() so that it manipulates scaled down versions of the images (see method decodeSampledBitmapFromUri taken from Android guide [Loading Large Bitmaps Efficiently](http://developer.android.com/training/displaying-bitmaps/load-bitmap.html)).
